### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by kimitrois** [lost-melody/hamster-tools#1]
RowHeight不能填入字母，比如原生的注音键盘这种我也不理解是什么的“5.32e+1”高度……
label 项在生成的代码中，不自动添加引号，试过的有当 label: @xxx 时，键盘会导入失败…… 手动   :%s/@xxx/"@xxx"后导入成功

**Comment by lost-melody** [comment]
- `rowHeight` 填入的是 *浮點數*, 可按 *小數* 理解, 帶 *e* 的寫法是 `1.23e-4` 等價於 `1.23 * 10^-4` 卽 `0.000123`, 所以通常填入常見等價形式卽可, 無須調整
- `label` 項轉義問題通過 `JSON.stringify(label)` 解決

**Comment by lost-melody** [comment]
fixed in [this commit](https://github.com/lost-melody/hamster-tools/commit/d6122717122b9c98990ca6a61d0a0fc2bd071eea).
